### ISSUE TITLE
测试报告_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#10]
测试报告
1.	网站主界面左侧的功能选项未与子界面连接，点击之后仍在主界面没有变化，可以与子界面连接，选中之后进入相应的子界面进行操作；
 
2.	Advanced Search操作目前没有实现，点击该选项仍然为主界面没有变化；
 
3.	在网页上方的折叠目录分级有些混乱，应该设定比较清晰的目录分级，例如一级目录为home；二级目录为Experiments、Prediction、Compare等；三级目录为二级目录的具体信息；
 
4.	进入实验列表后，创建新的实验只能在原来的实验编号下进行修改，不能直接添加新的实验，这样会导致之前的实验数据被覆盖，创建选项应该是添加新的实验编号；
5.	创建实验的信息里，应该添加实验人名称编辑项，目前全部默认为韩福宁，添加实际做实验的时间，目前为在网站中新建实验的时间；
 
6.	创建实验，在点击创建之后可以设置跳转回到实验列表界面，避免重复创建；
7.	实验项目和试样数据应该是联系在一起的，目前一个实验编号对应的一个试样，新建实验就是新的试样；
 
8.	实验列表界面的Go for prediction 应该跳转到预测界面，但是点击后没有变化；
 
9.	创建新的实验后，预测界面没有变动，仍然为原来的拟合曲线，应该实验列表里的数据与预测界面数据点实时对应，在新建实验数据后自动更新；
10.	在预测界面可以只显示拟合模式和预测模式名称，点击后显示对应的拟合曲线、对于图框和预测选项；
11.	在预测界面中，GCr15 Prediction Basquin 5-95%和GCr15 Prediction Basquin 5-95%图框没有出现拟合曲线；
12.	预测界面目前仅有拟合曲线，没有预测寿命的选项，应该添加一个输入数据（角度，扭矩，应力，应变等）然后显示预测寿命的编辑栏；
13.	新建实验材料应该建立新的项目，目前建立新的实验材料仍然只有QT800和GCr15两个实验项目；
 
14.	目前Compare功能还没有实现，应该添加该部分功能。

**Comment by StoneGo** [comment]
Good !
