### ISSUE TITLE
网站主界面左侧的功能选项未与子界面连接_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#11]
1.	网站主界面左侧的功能选项未与子界面连接，点击之后仍在主界面没有变化，可以与子界面连接，选中之后进入相应的子界面进行操作；

**Comment by StoneGo** [comment]
不清楚你在说的是哪个，你详细描述一下吗？有些功能目前就是没有的，这个再讨论一下。
