### ISSUE TITLE
点击用户头像，会弹出试验和预测的选项框。

### ISSUE THREAD

**Issue by lananfeng** [CloudLab-BIT/webapp#12]
①	点击用户头像，会弹出试验和预测的选项框。
 
②	菜单栏顺序应当调整一下，在新建过程中，需要选择上一级的材料、试棒信息。
 
③	材料标准栏有内容无法显示。
 
④	无法新建试棒，且无法选择新材料创建试棒。
 
⑤	创建新试验时，数据类型应该是6列和3列，无12列选项。
 
⑥	删除某一材料、试验后，试验ID的编号不连续。
  
⑦	删除某一材料、试验后，界面不会自动刷新。
⑧	添加新材料后，在主界面没有相应材料的选项。
 
⑨	寿命预测界面，没有实现寿命预测的功能，仅实现了不同置信度条件下相关曲线的输出，且仍有部分曲线图内没有曲线。
⑩	暂无材料比较等功能。

**Comment by StoneGo** [comment]
理解，应修改

**Comment by StoneGo** [comment]
Fixed
