### ISSUE TITLE
2.	Advanced Search操作目前没有实现，点击该选项仍然为主界面没有变化；

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#13]
2.	Advanced Search操作目前没有实现，点击该选项仍然为主界面没有变化；

**Comment by StoneGo** [comment]
目前可能也没啥可检索得，还不知道实现哪些检索，得跟龙老师他们碰一下。

**Comment by a15951005190** [comment]
好的，这个问题之前我也没想过，我是看到了您对这个功能的描述，2333。



在 2020-06-14 17:39:01，"StoneGo" <notifications@github.com> 写道：

目前可能也没啥可检索得，还不知道实现哪些检索，得跟龙老师他们碰一下。
