### ISSUE TITLE
在网页上方的折叠目录分级有些混乱，应该设定比较清晰的目录分级_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#14]
3.	在网页上方的折叠目录分级有些混乱，应该设定比较清晰的目录分级，例如一级目录为home；二级目录为Experiments、Prediction、Compare等；三级目录为二级目录的具体信息；

**Comment by StoneGo** [comment]
导航还是看左侧菜单，每个页面上的超链就是不太一样的昂。能给出具体描述就可以了，或者你们谁定一下怎么改。

**Comment by a15951005190** [comment]
这里我想一下大概怎么设定，之后再和您讨论吧。



在 2020-06-14 17:40:27，"StoneGo" <notifications@github.com> 写道：

导航还是看左侧菜单，每个页面上的超链就是不太一样的昂。能给出具体描述就可以了，或者你们谁定一下怎么改。
