### ISSUE TITLE
5.	创建实验的信息里，应该添加实验人名称编辑项，目前全部默认为韩福宁，添加实际做实验的时间，目前为在网站中新建实验的时间；

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#16]

**Comment by StoneGo** [comment]
目前现在就是这么设计的，测试的时候建立，时间不能随便修改。

**Comment by a15951005190** [comment]
这个建议主要是因为我们需要记录的是做实验的人和做实验的时间，方便我们之后查询，现在先这样也可以，郭老师我们后面再讨论这个问题。



在 2020-06-14 17:42:05，"StoneGo" <notifications@github.com> 写道：

目前现在就是这么设计的，测试的时候建立，时间不能随便修改。
