### ISSUE TITLE
7.	实验项目和试样数据应该是联系在一起的，目前一个实验编号对应的一个试样，新建实验就是新的试样_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#18]

**Comment by StoneGo** [comment]
可能是你理解有问题吧？实验名称是随便些的

**Comment by a15951005190** [comment]
不是名称的问题，我测试的时候，新建实验只能在已有的试样中选择，实际上应该是新建一个实验对应一个试样，例如目前GCr15有七组实验，七个试样，新建第八个实验的时候应该是对应试样8，而不是在之前的试样中选择。
这个问题我是这样理解的，如果我理解的不清晰，郭老师我们在微信详细说怎么样。



在 2020-06-14 17:44:33，"StoneGo" <notifications@github.com> 写道：

可能是你理解有问题吧？实验名称是随便些的
