### ISSUE TITLE
9.	创建新的实验后，预测界面没有变动，仍然为原来的拟合曲线，应该实验列表里的数据与预测界面数据点实时对应，在新建实验数据后自动更新_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#20]

**Comment by StoneGo** [comment]
这个要再后台算一遍，实时的分析现在做不到，超出本次项目范围。

**Comment by a15951005190** [comment]
昨天老师给我们开会的时候，老师说这个网站需要进行数据处理，不是单纯的调用已有的，我不清楚老师是怎么和您说得，等您有时间的时候我们碰一下吧。



在 2020-06-14 17:45:26，"StoneGo" <notifications@github.com> 写道：

这个要再后台算一遍，实时的分析现在做不到，超出本次项目范围。
