### ISSUE TITLE
13.	新建实验材料应该建立新的项目，目前建立新的实验材料仍然只有QT800和GCr15两个实验项目_An

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#33]

**Comment by StoneGo** [comment]
这个不一定吧？不太理解你说的是啥意思 实验项目有好多个呢

**Comment by a15951005190** [comment]
目前主界面只有QT800和GCr15，我的意思是在材料列表添加新的材料之后，应该也能对新的材料进行信息录入和预测，例如我在材料列表添加A357材料，应该同样可以对其进行实验信息录入和预测寿命。可能我说的实验项目表达有问题，您如果不理解我们再讨论。



在 2020-06-14 17:58:02，"StoneGo" <notifications@github.com> 写道：

这个不一定吧？不太理解你说的是啥意思 实验项目有好多个呢

**Comment by StoneGo** [comment]
建完材料之后，先增加试棒，然后才能再做实验
