### ISSUE TITLE
最后一列Report内容与第一列ID里面的report内容一样，可以将ID里面的report部分去掉，保留最后一列的Report。byYang

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#38]
![yang2](https://user-images.githubusercontent.com/59333558/84589389-abc30680-ae60-11ea-99a7-cb695611a3ba.png)

**Comment by StoneGo** [comment]
理解，去掉

**Comment by StoneGo** [comment]
你的测试是错的
