### ISSUE TITLE
要对数据进行排序或按不同标准进行分类排序，例如按日期排序、按试验寿命排序等byYang

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#40]
![yang3](https://user-images.githubusercontent.com/59333558/84589415-f0e73880-ae60-11ea-8aa4-e8a7f98f9d19.png)

**Comment by StoneGo** [comment]
可能没必要哦 目前也没多少实验 做这个也挺麻烦的 可以降低优先级
