### ISSUE TITLE
新建试棒问题。目前无法正常增加试棒。

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#46]
如图 1 New Specimen错误所示，填好试棒信息后，无法创建。点击creat按钮，在Specimen List没有显示新增加的试棒。并且在选择新材料时会提示Material must be in 1 and n。如图 2 New Specimen选新材料错误所示。
![gaotian1](https://user-images.githubusercontent.com/59333558/84589510-85519b00-ae61-11ea-8549-ccdebb75e730.png)
![gaotian2](https://user-images.githubusercontent.com/59333558/84589511-8682c800-ae61-11ea-8fc5-191901eb3066.png)

**Comment by StoneGo** [comment]
duplicated by #25
