### ISSUE TITLE
目前暂未找各循环的相关参数。

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#49]
如图所示，在LCF的软件中能通过data标签展示试棒各周期的相关参数。数据管理系统应该后期也保存相关数据，方便查阅。
![datashow](https://user-images.githubusercontent.com/59333558/84589591-4f60e680-ae62-11ea-9e3a-0a5592223058.png)

**Comment by StoneGo** [comment]
这个真需要展示吗？

**Comment by StoneGo** [comment]
保存在数据库里，有需要展示的吗？
