### ISSUE TITLE
Data Management功能暂时没有（相关数据未保存，LCF最后一界面）。

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#51]
在LCF中，最后一个界面，可以选择材料和试棒，可以检索出当前试棒的基础信息和滞回环参数，可以快速查看试棒分析后的参数。数据管理系统应该在试棒中或者其他界面保存这一实验结果，同时可以进行检索。

**Comment by StoneGo** [comment]
不太懂 得给我讲讲 有必要做的话再说

**Comment by StoneGo** [comment]
保存了 在数据库里
