### ISSUE TITLE
HCF录入数据（WriteData.m）

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#61]
function [SpecName_1]=WriteData(SpecName_1,FatigueLife_1,Stress_1,Diameter_1,Frequncy_1,MaxTorque_1,FracturedLocs_1,MinTorque_1,MaxTheta_1,MinTheta_1,Length_1,RunoutCycle_1,RunoutTime_1,Image_1_1,Image_2_1,Image_3_1,Materials,Type)
Excel_name='Material_List.xlsx';

SheetType=strcat('_',Type);
SheetName = strcat(Materials,SheetType);
if ismember(SheetName,app.Sheet_name)
[~,SpecName]  = xlsread(Excel_name,SheetName,'A1:A20');
[~,~,FatigueLife]  = xlsread(Excel_name,SheetName,'B1:B20');
[~,~,Stress]  = xlsread(Excel_name,SheetName,'C1:C20');
[~,~,Diameter]  = xlsread(Excel_name,SheetName,'D1:D20');
[~,~,Frequncy]  = xlsread(Excel_name,SheetName,'E1:E20');
[~,~,MaxTorque]  = xlsread(Excel_name,SheetName,'F1:F20');
[~,FracturedLocs]  = xlsread(Excel_name,SheetName,'G1:G20');
[~,~,MinTorque]  = xlsread(Excel_name,SheetName,'H1:H20');
[~,~,MaxTheta]  = xlsread(Excel_name,SheetName,'I1:I20');
[~,~,MinTheta]  = xlsread(Excel_name,SheetName,'J1:J20');
[~,~,Length]  = xlsread(Excel_name,SheetName,'K1:K20');
[~,~,RunoutCycle]  = xlsread(Excel_name,SheetName,'L1:L20');
[~,~,RunoutTime]  = xlsread(Excel_name,SheetName,'M1:M20');
[~,Image_1]  = xlsread(Excel_name,SheetName,'N1:N20');
[~,Image_2]  = xlsread(Excel_name,SheetName,'O1:O20');
[~,Image_3]  = xlsread(Excel_name,SheetName,'P1:P20');
len = length(SpecName);
SpecName{len+1,1} = SpecName_1;
Diameter{len+1,1} =  Diameter_1;
MaxTorque{len+1,1} = MaxTorque_1;
FatigueLife{len+1,1} =  FatigueLife_1;
Frequncy{len+1,1} = Frequncy_1;
Stress{len+1,1} =  Stress_1;
FracturedLocs{len+1,1} = FracturedLocs_1;
MinTorque{len+1,1} = MinTorque_1;
MaxTheta{len+1,1} = MaxTheta_1;
MinTheta{len+1,1} =  MinTheta_1;
Length{len+1,1} = Length_1;
RunoutCycle{len+1,1} = RunoutCycle_1;
RunoutTime{len+1,1} =  RunoutTime_1;
Image_1{len+1,1} = Image_1_1;
Image_2{len+1,1} = Image_2_1;
Image_3{len+1,1} = Image_3_1;

xlswrite(Excel_name,SpecName,SheetName,'A1');
xlswrite(Excel_name,FatigueLife,SheetName,'B1');
xlswrite(Excel_name,Stress,SheetName,'C1');
xlswrite(Excel_name,Diameter,SheetName,'D1');
xlswrite(Excel_name,Frequncy,SheetName,'E1');
xlswrite(Excel_name,MaxTorque,SheetName,'F1');
xlswrite(Excel_name,FracturedLocs,SheetName,'G1');
xlswrite(Excel_name,MinTorque,SheetName,'H1');
xlswrite(Excel_name,MaxTheta,SheetName,'I1');
xlswrite(Excel_name,MinTheta,SheetName,'J1');
xlswrite(Excel_name,Length,SheetName,'K1');
xlswrite(Excel_name,RunoutCycle,SheetName,'L1');
xlswrite(Excel_name,RunoutTime,SheetName,'M1');
xlswrite(Excel_name,Image_1,SheetName,'N1');
xlswrite(Excel_name,Image_2,SheetName,'O1');
xlswrite(Excel_name,Image_3,SheetName,'P1');
end

**Comment by StoneGo** [comment]
代码提交到repository, 不是issue
