### ISSUE TITLE
HCF预测寿命（SN.m）

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#62]
function [m,C,N_1,N_5,N_50,N_95,N_99]=SN(Materials,Type,MaxTorque,MinTorque,Diametermm)
Excel_name='Material_List.xlsx';
SheetType=strcat('_',Type);
SheetName = strcat(Materials,SheetType);

[FatigueLife]  = xlsread('Material_List.xlsx',SheetName,'B1:B20');
[Stress]  = xlsread('Material_List.xlsx',SheetName,'C1:C20');
S=Stress;
Nf=FatigueLife;
tor_a=(MaxTorque-MinTorque)/2;
S_prediction=8*tor_a*1000/pi/Diametermm^3;

%'50%'
miu = 0;
[N1,S_Ne,S_50,S_P,m,C] = S_N_P(S,Nf,miu);
figure;
semilogx(Nf,S,'k*');
hold on
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1,S_50,'g');
legend('数据点','p=50%');
N_50=C/(S_prediction^m);

%'5%-95%'
miu = 1.645;
[N1,S_Ne,~,S_P,~,~] = S_N_P(S,Nf,miu);
figure;
semilogx(Nf,S,'k*');hold on
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1,S_Ne,'k');
semilogx(N1,S_P,'r');
legend('数据点','p=5%','p=95%');
[N_5,N_95] = N_MinMax(Stress,FatigueLife,miu,S_prediction);

%'1%-99%'
miu = 2.326;
[N1,S_Ne,~,S_P,~,~] = S_N_P(S,Nf,miu);
figure;
semilogx(Nf,S,'k*');hold on
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1,S_Ne,'k');
semilogx(N1,S_P,'r');
legend('数据点','p=1%','p=99%');
[N_1,N_99] = N_MinMax(Stress,FatigueLife,miu,S_prediction);

end

**Comment by StoneGo** [comment]
代码提交到repository, 不是issue
