### ISSUE TITLE
HCF材料比较

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#63]
function [m_1,C_1,m_2,C_2]=Compare(Materials_1,Type_1,Materials_2,Type_2)
Excel_name='Material_List.xlsx';
SheetType_1=strcat('_',Type_1);
SheetName_1 = strcat(Materials_1,SheetType_1);

[FatigueLife_1]  = xlsread('Material_List.xlsx',SheetName_1,'B1:B20');
[Stress_1]  = xlsread('Material_List.xlsx',SheetName_1,'C1:C20');
S_1=Stress_1;
Nf_1=FatigueLife_1;

SheetType_2=strcat('_',Type_2);
SheetName_2 = strcat(Materials_2,SheetType_2);

[FatigueLife_2]  = xlsread('Material_List.xlsx',SheetName_2,'B1:B20');
[Stress_2]  = xlsread('Material_List.xlsx',SheetName_2,'C1:C20');
S_2=Stress_2;
Nf_2=FatigueLife_2;

%'50%'
miu = 0;
[N1_1,S_Ne_1,S_50_1,S_P_1,m_1,C_1] = S_N_P(S_1,Nf_1,miu);
[N1_2,S_Ne_2,S_50_2,S_P_2,m_2,C_2] = S_N_P(S_1,Nf_1,miu);
figure;
semilogx(Nf_1,S_1,'k*');hold on
semilogx(Nf_2,S_2,'r*');
hold on
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1_1,S_50_1,'k');
semilogx(N1_2,S_50_2,'r');
% legend('数据点','p=50%');

%'5%-95%'
miu = 1.645;
[N1_1,S_Ne_1,~,S_P_1,~,~] = S_N_P(S_1,Nf_1,miu);
[N1_2,S_Ne_2,~,S_P_2,~,~] = S_N_P(S_2,Nf_2,miu);
figure;
semilogx(Nf_1,S_1,'k*');hold on
semilogx(Nf_2,S_2,'k*');
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1_1,S_Ne_1,'k');
semilogx(N1_1,S_P_1,'k');
semilogx(N1_2,S_Ne_2,'r');
semilogx(N1_2,S_P_2,'r');

% legend('数据点','p=5%','p=95%');

%'1%-99%'
miu = 2.326;
[N1_1,S_Ne_1,~,S_P_1,~,~] = S_N_P(S_1,Nf_1,miu);
[N1_2,S_Ne_2,~,S_P_2,~,~] = S_N_P(S_2,Nf_2,miu);
figure;
semilogx(Nf_1,S_1,'k*');hold on
semilogx(Nf_2,S_2,'k*');
xlabel('N');
ylabel('Stress/MPa');
title('Stress-N Curve');
semilogx(N1_1,S_Ne_1,'k');
semilogx(N1_1,S_P_1,'k');
semilogx(N1_2,S_Ne_2,'r');
semilogx(N1_2,S_P_2,'r');

end

**Comment by StoneGo** [comment]
代码提交到repository, 不是issue
