### ISSUE TITLE
HCF函数（N_MinMax）

### ISSUE THREAD

**Issue by a15951005190** [CloudLab-BIT/webapp#65]
function [N_Min,N_Max] = N_MinMax(tau,Nf,miu,S)

x=log10(Nf);y=log10(tau);%应力循环
p=polyfit(x,y,1);

yFit=polyval(p,x);
m=-(1/p(1));
C=10^(p(2)*m);
% figure;
% plot(x,y,'k*');hold on
% plot(x, polyval(p, x));hold on

% xlabel('log10(N)');
% ylabel('log10(stress)');
% title('log10(N)-log10(stress)');

n=length(Nf);X=0;Y=0;Q=0;xi2=0;yi2=0;xiyi=0;   

for i=1:n %求X和Y的平均值
    X=X+x(i);
    Y=Y+y(i);
end
Xb=X/n;
Yb=Y/n;
for i=1:n %求估计量与实际值的偏差平方和Q
    Q=Q+(polyval(p,x(i))-y(i))^2;
end
for i=1:n %求相关系数r和Lxx、Lyy、Lxy
    xi2=xi2+x(i)^2;
    yi2=yi2+y(i)^2;
    xiyi=xiyi+x(i)*y(i);
end

Lxx=xi2-X^2/n;
Lyy=yi2-Y^2/n;
Lxy=xiyi-X*Y/n;
r=Lxy/(Lxx*Lyy)^0.5;

xp=[2:0.001:5]
% syms y_5 y_50 y_95 xp;
y_50=p(1)*xp+p(2);
s=((Lyy-p(1)^2*Lxx)/(n-2))^0.5;
y_N=y_50-miu*s;
y_P=y_50+miu*s;
% figure;
% plot(x,y,'k*');hold on
% plot(xp,y_5,'g');hold on
% plot(xp,y_50,'r');hold on
% plot(xp,y_95,'k');
% legend('S1-S7','p=5%','p=50%','p=95%')
% xlabel('log(N)');
% ylabel('log(S)');
% title('loglog(N-S)');
% axis([2 6 -3.5 -1])
N1=[10:10:1000000];
N2=log10(N1);
S_50=10.^(p(2))*10.^(p(1)*N2);
S_Ne=10.^(p(2)-miu*s)*10.^(p(1)*N2);
S_P=10.^(p(2)+miu*s)*10.^(p(1)*N2);

N_Min=10^(log10(S/10.^(p(2)-miu*s))/p(1));
N_Max=10^(log10(S/10.^(p(2)+miu*s))/p(1));

end

**Comment by StoneGo** [comment]
代码提交到repository, 不是issue
