### ISSUE TITLE
测试反馈byYang（杨梦迪）

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#8]
通过试用寿命预测系统，我感觉整体上内容是比较丰富的，各项功能也比较完善。下面是我根据我自己的试用体验，针对界面显示和部分内容提出一点个人的建议。下面的建议都是以GCr15为例提出的，QT800同理。
1 选择材料的experiment之后，点击每次测试的ID进入如下界面，界面上1和2红色方框内的内容是一样的，建议保留其中一个红色方框。
![Uploading yang1.png…]()
2 上图红色方框3中的三行为可点击的状态，但是点进去没有内容，建议改成不可点击的状态或者增加相关内容。
3 每一个图的名称，建议放在图的左上角位置。
4 最后一列Report内容与第一列ID里面的report内容一样，可以将ID里面的report部分去掉，保留最后一列的Report。
![Uploading yang2.png…]()
5 添加/删除数据的按钮不明显或者未设置。对于GCr15来说，显示的有6组数据，如果用户想手动加入一组数据，不确定应该怎么加。
6 要对数据进行排序或按不同标准进行分类排序，例如按日期排序、按试验寿命排序等。
![yang3](https://user-images.githubusercontent.com/59333558/84587536-9f37b180-ae52-11ea-964a-726cf5c6b110.png)
7 用户ID应该可以根据用户添加或删除数据进行实时更新。
8 点击Experiment中的GO For GCr15 Prediction之后没有反应，建议直接跳转Home界面中的Prediction，显示预测图。
![yang4](https://user-images.githubusercontent.com/59333558/84587540-a65ebf80-ae52-11ea-89fb-eb7bd3f1657f.png)
9 在prediction界面，绘制完滞回环或应力应变曲线之后的寿命预测相关参数以及每一个循环的参数没有显示。
10显示的曲线可以根据用户不同的需求进行设置，例如图片大小、图上数据的实时显示等，并且应该可以使用户自由选择自己想要看的曲线或者不同公式下显示的曲线。
11 根据不同的预测方法绘制出曲线之后，没有预测误差的显示。

**Comment by StoneGo** [comment]
GOOD!
