### ISSUE TITLE
测试反馈byGT(高天天)

### ISSUE THREAD

**Issue by tiangao-bit** [CloudLab-BIT/webapp#9]
web扭转试验数据管理系统已经实现了扭转试验数据数据的保存、管理、查看结果等功能。自己经过使用和测试，针对功能和界面发现了以下问题并提出了个人想法和建议。
## 功能方面问题与建议
1. 新建试棒问题。目前无法正常增加试棒，如图 1 New Specimen错误所示，填好试棒信息后，无法创建。点击creat按钮，在Specimen List没有显示新增加的试棒。并且在选择新材料时会提示Material must be in 1 and n。如图 2 New Specimen选新材料错误所示。
![gaotian1](https://user-images.githubusercontent.com/59333558/84587814-ff2f5780-ae54-11ea-84bc-76de2daf1d90.png)
![gaotian2](https://user-images.githubusercontent.com/59333558/84587815-00f91b00-ae55-11ea-810e-74610908607c.png)
2. 在Experiment Report中的滞回环目前只能查看上传的特定某一周期。不能输入周期数，显示其滞回环。同时在Report中，曲线都是以图像格式展示，不能显示选定点的横纵坐标。不能精确从图片中获取信息同时，Report中没有显示试验中最大最小应力应变，平均应力应变，选定周期的G值，弹性塑形应变等具体参数。
3. Prediction和Experiment Report的问题一致。在用不同算法预测曲线展示曲线上，无法获得精确坐标值。同时暂无预测寿命参数具体显示，如预测寿命值，与实际误差值等等。
4. 目前暂未找各循环的相关参数。如图 3 LCF Datashow所示，在LCF的软件中能通过data标签展示试棒各周期的相关参数。数据管理系统应该后期也保存相关数据，方便查阅。
![gaotian3](https://user-images.githubusercontent.com/59333558/84587819-08b8bf80-ae55-11ea-9ffd-3abe8a120332.png)
5. Compare模块暂无对比界面，目前数据管理系统在每个材料的Prediction中，展示了εe-N的曲线，Compare模块中应该直观展示两种材料的曲线对比，以及材料计算分析后参数sigmaF，b，epsilon，c，k等的对比。之后，可以将Compare做成单独的界面，可选对比材料，对比参数等信息，并直观的表现出来。
6. Data Management功能暂时没有（相关数据未保存）。在LCF中，最后一个界面，可以选择材料和试棒，可以检索出当前试棒的基础信息和滞回环参数，可以快速查看试棒分析后的参数。数据管理系统应该在试棒中或者其他界面保存这一实验结果，同时可以进行检索。
7. 在web数据管理系统上，目前还未找到能在线分析，或者进行与matlab交互分析的功能。暂时只能查找到已经在matlab上做过分析试棒的数据和结果，如果需要用某种算法来预测试棒寿命，而上传数据中没有此算法分析的结果。之后应该能在线提交分析申请，让matlab在后台分析，完成后，提示用户完成分析并查看结果。
8. 如何上传matlab分析结果图表？
9. 如何新建试棒？
##  操作交互界面的问题与建议
1. 账号相关。目前大家都使用superuser账户登录，意味着所有用户的权限是一样的。在正式使用阶段应该区分不同的使用人员。权限也应该不一样。如某次实验数据Adata为A人员操作并上传，那么修改上传权限应该为A或者管理员拥有。防止其他用户误改、误操作、误上传。
2. 在菜单栏如图 4菜单栏所示中点任一按钮，目前都是跳转回Dashboard主界面。在后期使用可以丰富菜单栏中各功能。如users为管理员新建、修改其他用户操作。settings可以允许有相关权限的人员修改数据管理系统的设置，具体设置可以有界面相关设置，如界面风格，配色。数据展示范围，如选择双缸原始数据的电缸位移量（幅值）、力值是否显示，预测算法的选择等等系统设置。 可设置为通知提醒功能，铃铛图标可提醒是否有同组其他新数据上传，在线试验试棒失效，设备异常等功能。
![gaotian4](https://user-images.githubusercontent.com/59333558/84587804-ec1c8780-ae54-11ea-99e6-ab39ad72f096.png)
3.  在Modify Experiment中，修改完成后，应该弹出修改完成或者是否保存提示。在试验信息修改时，点击 ，目前没有任何提示。会使操作人员不清楚是否修改成功，只能再次进如Experiment Details界面查看数据是否修改。应该弹出对话框是否保存修改或者保存成功等交互，方便使用。 creat按钮也能加入创建成功或者是否创建提示弹窗。
4. 在Material中新建了某一种材料，在Dashboard主界面中，未能像QT800和GCr15有直接进入Experment和Prediction的材料色块。

**Comment by StoneGo** [comment]
GOOD !
